ModOrganizer2/usvfs

.gitignore
vsbuild/external_dependencies.props
vsbuild/udis86.vcxproj

external dependencies can now be overwritten either with environment variables or by creating
a vsbuild/external_dependencies_local.props file.
additionally, we use "py -2" by default to support cases where both python 2 and python 3 are
installed and python 3 is the default (without the need to overwrite the PYTHON2_CMD).

Allow overwriting paths to external dependencies and default to "py -2"

---

src/shared/wildcard.cpp
src/usvfs_dll/hooks/kernel32.cpp
src/usvfs_dll/hooks/ntdll.cpp

* Detect cross-drive directory moves and use an alternate (working) method
* Recursively add new directories to the VFS
* Fix up returned errors with moves
* Allow moved files to be placed back in the same location
* Fix up handling of FFF / ntQDF search strings and correctly reroute based on valid non-search path
* Fix up FFF handling of relative paths
* Fix up ntQDF hook problem with dot characters represented as " when passed in
* Use the calculated Temp path for the FFF hook exclusion

Wrye Bash (and other) fixes

---

src/shared/directory_tree.h
src/usvfs_dll/hooks/kernel32.cpp
src/usvfs_dll/hooks/ntdll.cpp

The problem with WB file in use was with a handle opened by FindFirstFile was getting leaked in case ntQueryDirecoryFile was not called until STATUS_NO_MORE_FILES, as the structure containing the pointer to the handle was erased before getting closed.
The problem with xEdit not being able to rename files (save the working copy) was due to MoveFile hook removing the source file twice from the directory tree in case the move was across drives (overwrite and Data on different drives when cleaning downguard) . In case of different drives MoveFile internally useses copy + delete, problem is that both the MoveFile hook and the DeleteFile hook removed the file from mapping. This fix does not actually resolve this, simply makes it so that removing a file that does no longer exist in the mapping …

Fix for WB file in use and xEdit renaming fail.

---

include/usvfs.h
include/usvfsparameters.h
src/usvfs_dll/usvfs.cpp

This adds a parameter to `USVFSInitParameters()` to add a `Sleep()` call before the hooked process is resumed. It is 0 by default. When set to something like 10 seconds, it gives time to attach a debugger to the hooked process before it actually starts.
It's currently unused by MO, but I plan to add a setting in the ini, and perhaps a widget in the Diagnostics tab.

Delay parameter

---

src/usvfs_dll/hooks/kernel32.cpp

This is a targeted fix for the CK when saving files across drives. Note that usvfs has problems with relative paths and those are currently only handled manually in a few hooks as problems arise.

Handle relative paths in the DeleteFileW() hook

---

src/usvfs_dll/hookcontext.cpp
src/usvfs_dll/hookcontext.h

Turns out parameters are copied to the spawned process and the delay process setting wasn't.

Propagate the delay parameter to the spawned process

---

src/usvfs_dll/version.rc

Turns out there's _two_ `version.rc`.

Changed CompanyName and FileDescription

---

.gitignore
include/usvfs.h
include/usvfsparameters.h
include/usvfsparametersprivate.h
src/usvfs_dll/hookcontext.cpp
src/usvfs_dll/hookcontext.h
src/usvfs_dll/hookmanager.cpp
src/usvfs_dll/hookmanager.h
src/usvfs_dll/hooks/kernel32.cpp
src/usvfs_dll/usvfs.cpp
src/usvfs_dll/usvfsparameters.cpp
src/usvfs_helper/inject.cpp
src/usvfs_helper/inject.h
src/usvfs_proxy/main.cpp
src/usvfs_proxy/version.rc
vsbuild/usvfs_dll.vcxproj
vsbuild/usvfs_dll.vcxproj.filters

The problem this is trying to solve is that the old `USVSParameters` structure, `USVFSInitParameters()` and `USVFSUpdateParams()` can't be modified without breaking the ABI. I wanted to add the spawn delay parameter, but then the DLL wouldn't be compatible with 2.2.1. I don't want to pick and choose changes to release patches to usvfs.
This PR completely deprecates `USVSParameters` as well as its associated functions, and changes all the internals to use the new `usvfsParameters` instead. The two structures are basically identical (except for the new spawn delay), but `usvfsParameters` is not exposed, it's just an opaque pointer. It also starts a long-term process of adding the `usvfs` prefix to the public interface, because stuff like `GetLogMessages()` isn't great.
Specifically, these …

New parameters structure

---

include/sharedparameters.h
include/usvfs.h
include/usvfsparameters.h
src/usvfs_dll/hookcontext.cpp
src/usvfs_dll/hookcontext.h
src/usvfs_dll/sharedparameters.cpp
src/usvfs_dll/usvfs.cpp
src/usvfs_dll/usvfsparameters.cpp
src/usvfs_proxy/main.cpp
vsbuild/usvfs_dll.vcxproj
vsbuild/usvfs_dll.vcxproj.filters

I had an intermittent crash when checking if an executable is blacklisted. My guess is that it was actually because the process list became corrupted, since it wasn't protected by a mutex. Multiple processes would add and remove themselves from that list without synchronization.
- I moved everything to `sharedparameters.h` and `sharedparameters.cpp`;
- I made all the fields private and added convenience functions to hide shared memory manipulations;
- I added a `m_mutex` that's locked for every operation.
I decided against using multiple mutexes because the only time the shared parameters are used is when settings change, or a process is started and terminated. I didn't feel like the added complexity was worth it.
Goes with https://github.com/ModOrganizer2/modorganizer/pull/885.

Protect shared parameters with a mutex

---

include/usvfs.h
src/usvfs_dll/usvfs.cpp

Added `GetVFSProcessList2()`, which allocates the buffer with all the process ids instead.

added GetVFSProcessList2() to return all the pids

---

src/usvfs_dll/hookcontext.cpp

to avoid resizing on even small/empty setups.
Sizes were chosen based on empirical observation.

Increase initial allocation size of shared memory

---

src/shared/directory_tree.h

- `activateSHM()` now also sets `m_TreeMeta` so it's self-contained
- `createOrOpen()` returns the name of the previous block if it must be destroyed
- all dead blocks are kept in a vector in `reassign()` and destroyed at the very end; the `remove()` call can still be recursive, but it's safe
- added a novel, I can send signed copies if anybody wants

Fix rare crash because reassign() could be recursive

---

src/shared/directory_tree.cpp
src/shared/directory_tree.h
src/shared/tree_container.h
src/usvfs_dll/usvfs.cpp

Some optimizations:
- Avoiding path iterators: `DecomposablePath` keeps a `string_view` and plays with indexes to decompose a path into its components.
- Faster extension check for the reverse tree: Since the extension of every file is checked, there's a new `extensionMatchesCI()` that compares extensions without memory allocation.
- Avoiding unnecessary strings: Pass more `string_view`s around, changed `CILess` to support them, changed `addNode()` to avoid creating shared strings if they're not needed. `CILess` now uses `_strnicmp()` because `string_view`s might not be null terminated.
- I changed `addFile()` and `addDirectory()` in `TreeContainer` to stop using recursion when reassigning the blocks and to retry outside of the catch. It was confusing the profiler, all the stuff that …

Optimizations

---

src/shared/stringutils.cpp
src/shared/stringutils.h
src/shared/tree_container.h
src/usvfs_dll/usvfs.cpp

This changes the algorithm for finding the newest shared memory block when the current one is outdated. Fixes https://github.com/ModOrganizer2/modorganizer/issues/1322.
When the current block is outdated, instead of just picking the next one, `reassign()` will check up to 100 names to find an existing one that's not outdated. This handles the case where a process has created and destroyed more than one block before other processes had the time to check theirs.
Note that the current shm name is actually kept in the shared parameters, that's how a new process knows which block to start with, but 1) `TreeContainer` doesn't have access to the parameters, and 2) the name is only updated when running a new process (both from MO and in the `CreateProcess()` hook), so it's not always up to date. …

Stale blocks

---

src/usvfs_dll/hooks/ntdll.cpp

I added a hardcoded check for files starting with "\Device\\" and forward them directly. Fixes https://github.com/ModOrganizer2/modorganizer/issues/1229.

Fix for spurious "Device" directories

---

src/usvfs_dll/usvfs.cpp

`is_directory` returns false for symbolic links and reparse points. This, combined with the fact that USVFS walks up the directory chain when adding an entry to the redirection tree, causes overlays to fail for directories where the path contains a symbolic link or a reparse point.
While that's fine for most users, people who use symbolic links to manage their game collection, or people who mount another disk in a NTFS directory, would be unable to overlay anything inside this game directory. It turns out that with the way Wine works internally, most Linux users actually have such a setup by default, and as of wine commit wine-mirror/wine@6b498d98a86b5179a025afbaaeaa3d60a8bd74ec, which exposes this internal detail to Win32 software, USVFS no longer works.
Changing the function from …

Switch is_directory to exists in assertPathExists

---

include/usvfs.h
src/usvfs_dll/hookcontext.h
src/usvfs_dll/hooks/kernel32.cpp
src/usvfs_dll/hooks/ntdll.cpp
src/usvfs_dll/usvfs.cpp
test/tvfs_test/main.cpp
test/usvfs_test/usvfs_test_base.cpp
vsbuild/asmjit.vcxproj
vsbuild/fmt.vcxproj
vsbuild/shared.vcxproj
vsbuild/shared_test.vcxproj
vsbuild/spdlog.vcxproj
vsbuild/test_file_operations.vcxproj
vsbuild/testinject_bin.vcxproj
vsbuild/testinject_dll.vcxproj
vsbuild/thooklib.vcxproj
vsbuild/thooklib_test.vcxproj
vsbuild/tinjectlib.vcxproj
vsbuild/tinjectlib_test.vcxproj
vsbuild/tvfs_test.vcxproj
vsbuild/udis86.vcxproj
vsbuild/usvfs_dll.vcxproj
vsbuild/usvfs_helper.vcxproj
vsbuild/usvfs_proxy.vcxproj
vsbuild/usvfs_test.vcxproj
vsbuild/usvfs_test_runner.vcxproj

* Remove deprecated functions.
* Prefix all exposed USVFS function as usvfsXXX.

Clean USVFS namespace

---

src/usvfs_dll/hookmanager.cpp
src/usvfs_dll/hooks/kernel32.cpp
src/usvfs_dll/hooks/kernel32.h

- GetFileAttributes(Ex)A
- LoadLibraryExA
- GetModuleFileNameA
Admittedly only GetModuleFileNameA is a known issue
I believe this supersedes #72

Readd some A hooks due to W11 changes

---

src/usvfs_dll/hookmanager.cpp
src/usvfs_dll/hooks/kernel32.cpp
src/usvfs_dll/hooks/kernel32.h

As of Windows 11 24H2 the implementation of `GetModuleFileNameA` does not call `GetModuleFileNameW`. So we must hook both functions.

Hook GetModuleFileNameA

---

src/usvfs_dll/hookcontext.cpp
src/usvfs_dll/hookcontext.h
src/usvfs_dll/hookmanager.cpp
src/usvfs_dll/usvfs.cpp

Small changes that uses [IsDebuggerPresent](https://learn.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-isdebuggerpresent) instead of a popup to wait for debugger.
Since this is non-blocking (compared to the previous popup), I also added a wait loop at the beginning of the injection process (very useful).
I also removed the debug attribute of `HookContext` since it was used nowhere.

Better debugging mode.
